
[[Dynamic-AssertionFailed]]
# AssertionFailed
:concept: Dynamic/AssertionFailed

.Synopsis
An assertion in the Rascal code is false.

.Syntax

.Types

.Function
`data RunTimeException = AssertionFailed() | AssertionFailed(str label);`

       
.Usage

.Description
An link:{RascalLang}#Assert[Assert] statement can be used to check assumptions during the execution of a Rascal program.
This error is generated if an assertion is not true.

Remedies:

*  Modify your code to make the assertion true.
*  Modify your assertion to reflect the current behaviour of your code.
*  Catch the `AssertionFailed` yourself, see link:{RascalLang}#TryCatch[try catch].


.Examples
[source,rascal-shell-error]
----
----
A false assertion gives an error:
[source,rascal-shell-error]
----
rascal>assert 3 > 4;
Assertion "" failed at |test-modules:///ConsoleInput.rsc|(36,13,<3,15>,<3,28>)
AssertionFailed("") at |test-modules:///ConsoleInput.rsc|(36,13,<3,15>,<3,28>)
Call stack (most recent first):
	main([]) at |test-modules:///ConsoleInput.rsc|(36,13,<3,15>,<3,28>)

ok
----
Define a function that only increments positive integers:
[source,rascal-shell-error]
----
rascal>int incrPositive(int n) { assert n > 0; return n + 1; }
ok
----
Calling it with a positive integer is fine:
[source,rascal-shell-error]
----
rascal>incrPositive(3);
int: 4
----
But a negative argument gives an error:
[source,rascal-shell-error]
----
rascal>incrPositive(-3);
Assertion "" failed at |test-modules:///ConsoleInput.rsc|(46,13,<2,26>,<2,39>)
AssertionFailed("") at |test-modules:///ConsoleInput.rsc|(46,13,<2,26>,<2,39>)
Call stack (most recent first):
	incrPositive(-3, {}) at |test-modules:///ConsoleInput.rsc|(46,13,<2,26>,<2,39>)
	main([]) at |test-modules:///ConsoleInput.rsc|(93,16,<5,15>,<5,31>)

ok
----
We can also catch the `AssertionFailed` error. First import the Rascal exceptions (which are also included in `Prelude`)
and `IO`:
[source,rascal-shell-error]
----
rascal>import Exception;
ok
rascal>import IO;
ok
rascal>try println(incrPositive(-3)); catch AssertionFailed(): println("incrPositive applied to an not positive argument");
Assertion "" failed at |test-modules:///ConsoleInput.rsc|(75,13,<4,26>,<4,39>)
AssertionFailed("") at |test-modules:///ConsoleInput.rsc|(75,13,<4,26>,<4,39>)
Call stack (most recent first):
	incrPositive(-3, {}) at |test-modules:///ConsoleInput.rsc|(75,13,<4,26>,<4,39>)
	main([]) at |test-modules:///ConsoleInput.rsc|(134,16,<7,27>,<7,43>)

ok
----

.Benefits

.Pitfalls


:leveloffset: +1

:leveloffset: -1